package org.tempurl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-21T09:33:07.266+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://tempurl.org", name = "n_smxtjkHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NSmxtjkHttpGet {

    @WebMethod(operationName = "opreation_arrangement")
    @WebResult(name = "string", targetNamespace = "http://tempurl.org", partName = "Body")
    public java.lang.String opreationArrangement(
        @WebParam(partName = "as_xml", name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "operation_blood")
    @WebResult(name = "string", targetNamespace = "http://tempurl.org", partName = "Body")
    public java.lang.String operationBlood(
        @WebParam(partName = "as_xml", name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "operation_inseryp")
    @WebResult(name = "string", targetNamespace = "http://tempurl.org", partName = "Body")
    public java.lang.String operationInseryp(
        @WebParam(partName = "as_xml", name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "opreation_modify")
    @WebResult(name = "string", targetNamespace = "http://tempurl.org", partName = "Body")
    public java.lang.String opreationModify(
        @WebParam(partName = "as_xml", name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );

    @WebMethod(operationName = "operation_inser")
    @WebResult(name = "string", targetNamespace = "http://tempurl.org", partName = "Body")
    public java.lang.String operationInser(
        @WebParam(partName = "as_xml", name = "as_xml", targetNamespace = "http://tempurl.org")
        java.lang.String asXml
    );
}
