
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-11-09T13:47:51.116+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class AIMSServiceSoap_AIMSServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "AIMSService");

    private AIMSServiceSoap_AIMSServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AIMSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AIMSService ss = new AIMSService(wsdlURL, SERVICE_NAME);
        AIMSServiceSoap port = ss.getAIMSServiceSoap();  
        
        {
        System.out.println("Invoking charge...");
        java.lang.String _charge_inputXml = "";
        java.lang.String _charge__return = port.charge(_charge_inputXml);
        System.out.println("charge.result=" + _charge__return);


        }
        {
        System.out.println("Invoking returnFee...");
        java.lang.String _returnFee_inpuXml = "";
        java.lang.String _returnFee__return = port.returnFee(_returnFee_inpuXml);
        System.out.println("returnFee.result=" + _returnFee__return);


        }
        {
        System.out.println("Invoking queryPatientListResult...");
        java.lang.String _queryPatientListResult_inputXml = "";
        java.lang.String _queryPatientListResult__return = port.queryPatientListResult(_queryPatientListResult_inputXml);
        System.out.println("queryPatientListResult.result=" + _queryPatientListResult__return);


        }
        {
        System.out.println("Invoking createUrgentOperation...");
        java.lang.String _createUrgentOperation_inputXml = "";
        java.lang.String _createUrgentOperation__return = port.createUrgentOperation(_createUrgentOperation_inputXml);
        System.out.println("createUrgentOperation.result=" + _createUrgentOperation__return);


        }
        {
        System.out.println("Invoking updateOperationStage...");
        java.lang.String _updateOperationStage_inputXml = "";
        java.lang.String _updateOperationStage__return = port.updateOperationStage(_updateOperationStage_inputXml);
        System.out.println("updateOperationStage.result=" + _updateOperationStage__return);


        }
        {
        System.out.println("Invoking queryPatientLisReport...");
        java.lang.String _queryPatientLisReport_inputXml = "";
        java.lang.String _queryPatientLisReport__return = port.queryPatientLisReport(_queryPatientLisReport_inputXml);
        System.out.println("queryPatientLisReport.result=" + _queryPatientLisReport__return);


        }
        {
        System.out.println("Invoking updateOperationApply...");
        java.lang.String _updateOperationApply_inputXml = "";
        java.lang.String _updateOperationApply__return = port.updateOperationApply(_updateOperationApply_inputXml);
        System.out.println("updateOperationApply.result=" + _updateOperationApply__return);


        }
        {
        System.out.println("Invoking updateOperationState...");
        java.lang.String _updateOperationState_inputXml = "";
        java.lang.String _updateOperationState__return = port.updateOperationState(_updateOperationState_inputXml);
        System.out.println("updateOperationState.result=" + _updateOperationState__return);


        }
        {
        System.out.println("Invoking queryPatientOrder...");
        java.lang.String _queryPatientOrder_inputXml = "";
        java.lang.String _queryPatientOrder__return = port.queryPatientOrder(_queryPatientOrder_inputXml);
        System.out.println("queryPatientOrder.result=" + _queryPatientOrder__return);


        }

        System.exit(0);
    }

}
