package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-11-09T13:47:51.271+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "AIMSServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AIMSServiceHttpGet {

    /**
     * 4.患者计费  version = 1.0
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Charge")
    public java.lang.String charge(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 7.患者退费
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ReturnFee")
    public java.lang.String returnFee(
        @WebParam(partName = "inpuXml", name = "inpuXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inpuXml
    );

    /**
     * 9.查询患者检验报告项目结果
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "QueryPatientListResult")
    public java.lang.String queryPatientListResult(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 6.创建急诊手术 version = 1.0
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CreateUrgentOperation")
    public java.lang.String createUrgentOperation(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 2.修改手术排台信息 version = 1.0
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateOperationStage")
    public java.lang.String updateOperationStage(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 8.查询患者检验报告
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "QueryPatientLisReport")
    public java.lang.String queryPatientLisReport(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 1.修改手术申请 version = 1.0
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateOperationApply")
    public java.lang.String updateOperationApply(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 3.修改手术状态 version = 1.0
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdateOperationState")
    public java.lang.String updateOperationState(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );

    /**
     * 5.患者医嘱查询 version = 1.0
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "QueryPatientOrder")
    public java.lang.String queryPatientOrder(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "http://tempuri.org/")
        java.lang.String inputXml
    );
}
