package cn.com.winning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-09-20T18:11:59.892+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://www.winning.com.cn/", name = "WebInterfaceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebInterfaceHttpGet {

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuHzxq(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuZcxx(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod(operationName = "HelloWorld")
    public java.lang.String helloWorld();

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String updateZt(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuZcrs(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuZkxx(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuCount(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String updateYs(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuHzxxCx(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuYzzxxx(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetPatientOrder")
    public java.lang.String getPatientOrder(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "string", targetNamespace = "http://www.winning.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String getIcuYzxx(
        @WebParam(partName = "requestXml", name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );
}
