package cn.com.winning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-09-20T18:11:59.999+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://www.winning.com.cn/", name = "WebInterfaceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebInterfaceSoap {

    @WebResult(name = "getIcuHzxqResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuHzxq", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuHzxq")
    @WebMethod(action = "http://www.winning.com.cn/getIcuHzxq")
    @ResponseWrapper(localName = "getIcuHzxqResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuHzxqResponse")
    public java.lang.String getIcuHzxq(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuZcxxResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuZcxx", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuZcxx")
    @WebMethod(action = "http://www.winning.com.cn/getIcuZcxx")
    @ResponseWrapper(localName = "getIcuZcxxResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuZcxxResponse")
    public java.lang.String getIcuZcxx(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://www.winning.com.cn/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.HelloWorldResponse")
    public java.lang.String helloWorld();

    @WebResult(name = "updateZtResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "updateZt", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.UpdateZt")
    @WebMethod(action = "http://www.winning.com.cn/updateZt")
    @ResponseWrapper(localName = "updateZtResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.UpdateZtResponse")
    public java.lang.String updateZt(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuZcrsResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuZcrs", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuZcrs")
    @WebMethod(action = "http://www.winning.com.cn/getIcuZcrs")
    @ResponseWrapper(localName = "getIcuZcrsResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuZcrsResponse")
    public java.lang.String getIcuZcrs(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuZkxxResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuZkxx", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuZkxx")
    @WebMethod(action = "http://www.winning.com.cn/getIcuZkxx")
    @ResponseWrapper(localName = "getIcuZkxxResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuZkxxResponse")
    public java.lang.String getIcuZkxx(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuCountResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuCount", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuCount")
    @WebMethod(action = "http://www.winning.com.cn/getIcuCount")
    @ResponseWrapper(localName = "getIcuCountResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuCountResponse")
    public java.lang.String getIcuCount(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "updateYsResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "updateYs", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.UpdateYs")
    @WebMethod(action = "http://www.winning.com.cn/updateYs")
    @ResponseWrapper(localName = "updateYsResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.UpdateYsResponse")
    public java.lang.String updateYs(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuHzxxCxResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuHzxxCx", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuHzxxCx")
    @WebMethod(action = "http://www.winning.com.cn/getIcuHzxxCx")
    @ResponseWrapper(localName = "getIcuHzxxCxResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuHzxxCxResponse")
    public java.lang.String getIcuHzxxCx(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuYzzxxxResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuYzzxxx", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuYzzxxx")
    @WebMethod(action = "http://www.winning.com.cn/getIcuYzzxxx")
    @ResponseWrapper(localName = "getIcuYzzxxxResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuYzzxxxResponse")
    public java.lang.String getIcuYzzxxx(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "GetPatientOrderResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "GetPatientOrder", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetPatientOrder")
    @WebMethod(operationName = "GetPatientOrder", action = "http://www.winning.com.cn/GetPatientOrder")
    @ResponseWrapper(localName = "GetPatientOrderResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetPatientOrderResponse")
    public java.lang.String getPatientOrder(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );

    @WebResult(name = "getIcuYzxxResult", targetNamespace = "http://www.winning.com.cn/")
    @RequestWrapper(localName = "getIcuYzxx", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuYzxx")
    @WebMethod(action = "http://www.winning.com.cn/getIcuYzxx")
    @ResponseWrapper(localName = "getIcuYzxxResponse", targetNamespace = "http://www.winning.com.cn/", className = "cn.com.winning.GetIcuYzxxResponse")
    public java.lang.String getIcuYzxx(
        @WebParam(name = "requestXml", targetNamespace = "http://www.winning.com.cn/")
        java.lang.String requestXml
    );
}
